// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/PhantomX7/dhamma/entity"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/PhantomX7/dhamma/utility/pagination"

	request "github.com/PhantomX7/dhamma/modules/user/dto/request"

	utility "github.com/PhantomX7/dhamma/utility"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AssignDomain provides a mock function with given fields: ctx, userID, _a2
func (_m *Service) AssignDomain(ctx context.Context, userID uint64, _a2 request.AssignDomainRequest) error {
	ret := _m.Called(ctx, userID, _a2)

	if len(ret) == 0 {
		panic("no return value specified for AssignDomain")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, request.AssignDomainRequest) error); ok {
		r0 = rf(ctx, userID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_AssignDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignDomain'
type Service_AssignDomain_Call struct {
	*mock.Call
}

// AssignDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - _a2 request.AssignDomainRequest
func (_e *Service_Expecter) AssignDomain(ctx interface{}, userID interface{}, _a2 interface{}) *Service_AssignDomain_Call {
	return &Service_AssignDomain_Call{Call: _e.mock.On("AssignDomain", ctx, userID, _a2)}
}

func (_c *Service_AssignDomain_Call) Run(run func(ctx context.Context, userID uint64, _a2 request.AssignDomainRequest)) *Service_AssignDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(request.AssignDomainRequest))
	})
	return _c
}

func (_c *Service_AssignDomain_Call) Return(_a0 error) *Service_AssignDomain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_AssignDomain_Call) RunAndReturn(run func(context.Context, uint64, request.AssignDomainRequest) error) *Service_AssignDomain_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *Service) Create(ctx context.Context, _a1 request.UserCreateRequest) (entity.User, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.UserCreateRequest) (entity.User, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.UserCreateRequest) entity.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.UserCreateRequest) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Service_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 request.UserCreateRequest
func (_e *Service_Expecter) Create(ctx interface{}, _a1 interface{}) *Service_Create_Call {
	return &Service_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *Service_Create_Call) Run(run func(ctx context.Context, _a1 request.UserCreateRequest)) *Service_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.UserCreateRequest))
	})
	return _c
}

func (_c *Service_Create_Call) Return(_a0 entity.User, _a1 error) *Service_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Create_Call) RunAndReturn(run func(context.Context, request.UserCreateRequest) (entity.User, error)) *Service_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function with given fields: ctx, pg
func (_m *Service) Index(ctx context.Context, pg *pagination.Pagination) ([]entity.User, utility.PaginationMeta, error) {
	ret := _m.Called(ctx, pg)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 []entity.User
	var r1 utility.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) ([]entity.User, utility.PaginationMeta, error)); ok {
		return rf(ctx, pg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) []entity.User); ok {
		r0 = rf(ctx, pg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pagination.Pagination) utility.PaginationMeta); ok {
		r1 = rf(ctx, pg)
	} else {
		r1 = ret.Get(1).(utility.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *pagination.Pagination) error); ok {
		r2 = rf(ctx, pg)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type Service_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - pg *pagination.Pagination
func (_e *Service_Expecter) Index(ctx interface{}, pg interface{}) *Service_Index_Call {
	return &Service_Index_Call{Call: _e.mock.On("Index", ctx, pg)}
}

func (_c *Service_Index_Call) Run(run func(ctx context.Context, pg *pagination.Pagination)) *Service_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pagination.Pagination))
	})
	return _c
}

func (_c *Service_Index_Call) Return(_a0 []entity.User, _a1 utility.PaginationMeta, _a2 error) *Service_Index_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Service_Index_Call) RunAndReturn(run func(context.Context, *pagination.Pagination) ([]entity.User, utility.PaginationMeta, error)) *Service_Index_Call {
	_c.Call.Return(run)
	return _c
}

// Show provides a mock function with given fields: ctx, userID
func (_m *Service) Show(ctx context.Context, userID uint64) (entity.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Show")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (entity.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type Service_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *Service_Expecter) Show(ctx interface{}, userID interface{}) *Service_Show_Call {
	return &Service_Show_Call{Call: _e.mock.On("Show", ctx, userID)}
}

func (_c *Service_Show_Call) Run(run func(ctx context.Context, userID uint64)) *Service_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Service_Show_Call) Return(_a0 entity.User, _a1 error) *Service_Show_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Show_Call) RunAndReturn(run func(context.Context, uint64) (entity.User, error)) *Service_Show_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
