// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/PhantomX7/dhamma/entity"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	pagination "github.com/PhantomX7/dhamma/utility/pagination"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, pg
func (_m *Repository) Count(ctx context.Context, pg *pagination.Pagination) (int64, error) {
	ret := _m.Called(ctx, pg)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) (int64, error)); ok {
		return rf(ctx, pg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) int64); ok {
		r0 = rf(ctx, pg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pagination.Pagination) error); ok {
		r1 = rf(ctx, pg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type Repository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - pg *pagination.Pagination
func (_e *Repository_Expecter) Count(ctx interface{}, pg interface{}) *Repository_Count_Call {
	return &Repository_Count_Call{Call: _e.mock.On("Count", ctx, pg)}
}

func (_c *Repository_Count_Call) Run(run func(ctx context.Context, pg *pagination.Pagination)) *Repository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pagination.Pagination))
	})
	return _c
}

func (_c *Repository_Count_Call) Return(_a0 int64, _a1 error) *Repository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Count_Call) RunAndReturn(run func(context.Context, *pagination.Pagination) (int64, error)) *Repository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1, tx
func (_m *Repository) Create(ctx context.Context, _a1 *entity.Domain, tx *gorm.DB) error {
	ret := _m.Called(ctx, _a1, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Domain, *gorm.DB) error); ok {
		r0 = rf(ctx, _a1, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Domain
//   - tx *gorm.DB
func (_e *Repository_Expecter) Create(ctx interface{}, _a1 interface{}, tx interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, _a1, tx)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, _a1 *entity.Domain, tx *gorm.DB)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Domain), args[2].(*gorm.DB))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 error) *Repository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(context.Context, *entity.Domain, *gorm.DB) error) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, pg
func (_m *Repository) FindAll(ctx context.Context, pg *pagination.Pagination) ([]entity.Domain, error) {
	ret := _m.Called(ctx, pg)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) ([]entity.Domain, error)); ok {
		return rf(ctx, pg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) []entity.Domain); ok {
		r0 = rf(ctx, pg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Domain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pagination.Pagination) error); ok {
		r1 = rf(ctx, pg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type Repository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - pg *pagination.Pagination
func (_e *Repository_Expecter) FindAll(ctx interface{}, pg interface{}) *Repository_FindAll_Call {
	return &Repository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, pg)}
}

func (_c *Repository_FindAll_Call) Run(run func(ctx context.Context, pg *pagination.Pagination)) *Repository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pagination.Pagination))
	})
	return _c
}

func (_c *Repository_FindAll_Call) Return(_a0 []entity.Domain, _a1 error) *Repository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindAll_Call) RunAndReturn(run func(context.Context, *pagination.Pagination) ([]entity.Domain, error)) *Repository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *Repository) FindByCode(ctx context.Context, code string) (entity.Domain, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 entity.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Domain, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Domain); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(entity.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type Repository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *Repository_Expecter) FindByCode(ctx interface{}, code interface{}) *Repository_FindByCode_Call {
	return &Repository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *Repository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *Repository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_FindByCode_Call) Return(_a0 entity.Domain, _a1 error) *Repository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByCode_Call) RunAndReturn(run func(context.Context, string) (entity.Domain, error)) *Repository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, domainID
func (_m *Repository) FindByID(ctx context.Context, domainID uint64) (entity.Domain, error) {
	ret := _m.Called(ctx, domainID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (entity.Domain, error)); ok {
		return rf(ctx, domainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) entity.Domain); ok {
		r0 = rf(ctx, domainID)
	} else {
		r0 = ret.Get(0).(entity.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, domainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - domainID uint64
func (_e *Repository_Expecter) FindByID(ctx interface{}, domainID interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, domainID)}
}

func (_c *Repository_FindByID_Call) Run(run func(ctx context.Context, domainID uint64)) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(_a0 entity.Domain, _a1 error) *Repository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (entity.Domain, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDomainRoles provides a mock function with given fields: ctx, domainID
func (_m *Repository) GetDomainRoles(ctx context.Context, domainID uint64) (entity.Domain, error) {
	ret := _m.Called(ctx, domainID)

	if len(ret) == 0 {
		panic("no return value specified for GetDomainRoles")
	}

	var r0 entity.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (entity.Domain, error)); ok {
		return rf(ctx, domainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) entity.Domain); ok {
		r0 = rf(ctx, domainID)
	} else {
		r0 = ret.Get(0).(entity.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, domainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetDomainRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDomainRoles'
type Repository_GetDomainRoles_Call struct {
	*mock.Call
}

// GetDomainRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - domainID uint64
func (_e *Repository_Expecter) GetDomainRoles(ctx interface{}, domainID interface{}) *Repository_GetDomainRoles_Call {
	return &Repository_GetDomainRoles_Call{Call: _e.mock.On("GetDomainRoles", ctx, domainID)}
}

func (_c *Repository_GetDomainRoles_Call) Run(run func(ctx context.Context, domainID uint64)) *Repository_GetDomainRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Repository_GetDomainRoles_Call) Return(_a0 entity.Domain, _a1 error) *Repository_GetDomainRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetDomainRoles_Call) RunAndReturn(run func(context.Context, uint64) (entity.Domain, error)) *Repository_GetDomainRoles_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1, tx
func (_m *Repository) Update(ctx context.Context, _a1 *entity.Domain, tx *gorm.DB) error {
	ret := _m.Called(ctx, _a1, tx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Domain, *gorm.DB) error); ok {
		r0 = rf(ctx, _a1, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Domain
//   - tx *gorm.DB
func (_e *Repository_Expecter) Update(ctx interface{}, _a1 interface{}, tx interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, _a1, tx)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, _a1 *entity.Domain, tx *gorm.DB)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Domain), args[2].(*gorm.DB))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 error) *Repository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(context.Context, *entity.Domain, *gorm.DB) error) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
