// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/PhantomX7/dhamma/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// AssignMultipleRole provides a mock function with given fields: ctx, userID, roleAssignments, tx
func (_m *Repository) AssignMultipleRole(ctx context.Context, userID uint64, roleAssignments []struct {
	DomainID uint64
	RoleID   uint64
}, tx *gorm.DB) error {
	ret := _m.Called(ctx, userID, roleAssignments, tx)

	if len(ret) == 0 {
		panic("no return value specified for AssignMultipleRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []struct {
		DomainID uint64
		RoleID   uint64
	}, *gorm.DB) error); ok {
		r0 = rf(ctx, userID, roleAssignments, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_AssignMultipleRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignMultipleRole'
type Repository_AssignMultipleRole_Call struct {
	*mock.Call
}

// AssignMultipleRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - roleAssignments []struct{DomainID uint64;RoleID uint64}
//   - tx *gorm.DB
func (_e *Repository_Expecter) AssignMultipleRole(ctx interface{}, userID interface{}, roleAssignments interface{}, tx interface{}) *Repository_AssignMultipleRole_Call {
	return &Repository_AssignMultipleRole_Call{Call: _e.mock.On("AssignMultipleRole", ctx, userID, roleAssignments, tx)}
}

func (_c *Repository_AssignMultipleRole_Call) Run(run func(ctx context.Context, userID uint64, roleAssignments []struct {
	DomainID uint64
	RoleID   uint64
}, tx *gorm.DB)) *Repository_AssignMultipleRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].([]struct {
			DomainID uint64
			RoleID   uint64
		}), args[3].(*gorm.DB))
	})
	return _c
}

func (_c *Repository_AssignMultipleRole_Call) Return(_a0 error) *Repository_AssignMultipleRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_AssignMultipleRole_Call) RunAndReturn(run func(context.Context, uint64, []struct {
	DomainID uint64
	RoleID   uint64
}, *gorm.DB) error) *Repository_AssignMultipleRole_Call {
	_c.Call.Return(run)
	return _c
}

// AssignRole provides a mock function with given fields: ctx, userID, domainID, roleID, tx
func (_m *Repository) AssignRole(ctx context.Context, userID uint64, domainID uint64, roleID uint64, tx *gorm.DB) error {
	ret := _m.Called(ctx, userID, domainID, roleID, tx)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, uint64, *gorm.DB) error); ok {
		r0 = rf(ctx, userID, domainID, roleID, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_AssignRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRole'
type Repository_AssignRole_Call struct {
	*mock.Call
}

// AssignRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - domainID uint64
//   - roleID uint64
//   - tx *gorm.DB
func (_e *Repository_Expecter) AssignRole(ctx interface{}, userID interface{}, domainID interface{}, roleID interface{}, tx interface{}) *Repository_AssignRole_Call {
	return &Repository_AssignRole_Call{Call: _e.mock.On("AssignRole", ctx, userID, domainID, roleID, tx)}
}

func (_c *Repository_AssignRole_Call) Run(run func(ctx context.Context, userID uint64, domainID uint64, roleID uint64, tx *gorm.DB)) *Repository_AssignRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64), args[3].(uint64), args[4].(*gorm.DB))
	})
	return _c
}

func (_c *Repository_AssignRole_Call) Return(_a0 error) *Repository_AssignRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_AssignRole_Call) RunAndReturn(run func(context.Context, uint64, uint64, uint64, *gorm.DB) error) *Repository_AssignRole_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID, preloadRelations
func (_m *Repository) FindByUserID(ctx context.Context, userID uint64, preloadRelations bool) ([]entity.UserRole, error) {
	ret := _m.Called(ctx, userID, preloadRelations)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entity.UserRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, bool) ([]entity.UserRole, error)); ok {
		return rf(ctx, userID, preloadRelations)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, bool) []entity.UserRole); ok {
		r0 = rf(ctx, userID, preloadRelations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, bool) error); ok {
		r1 = rf(ctx, userID, preloadRelations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type Repository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - preloadRelations bool
func (_e *Repository_Expecter) FindByUserID(ctx interface{}, userID interface{}, preloadRelations interface{}) *Repository_FindByUserID_Call {
	return &Repository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID, preloadRelations)}
}

func (_c *Repository_FindByUserID_Call) Run(run func(ctx context.Context, userID uint64, preloadRelations bool)) *Repository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(bool))
	})
	return _c
}

func (_c *Repository_FindByUserID_Call) Return(_a0 []entity.UserRole, _a1 error) *Repository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByUserID_Call) RunAndReturn(run func(context.Context, uint64, bool) ([]entity.UserRole, error)) *Repository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserIDAndDomainID provides a mock function with given fields: ctx, userID, domainID, preloadRelations
func (_m *Repository) FindByUserIDAndDomainID(ctx context.Context, userID uint64, domainID uint64, preloadRelations bool) ([]entity.UserRole, error) {
	ret := _m.Called(ctx, userID, domainID, preloadRelations)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserIDAndDomainID")
	}

	var r0 []entity.UserRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool) ([]entity.UserRole, error)); ok {
		return rf(ctx, userID, domainID, preloadRelations)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, bool) []entity.UserRole); ok {
		r0 = rf(ctx, userID, domainID, preloadRelations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64, bool) error); ok {
		r1 = rf(ctx, userID, domainID, preloadRelations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByUserIDAndDomainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserIDAndDomainID'
type Repository_FindByUserIDAndDomainID_Call struct {
	*mock.Call
}

// FindByUserIDAndDomainID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - domainID uint64
//   - preloadRelations bool
func (_e *Repository_Expecter) FindByUserIDAndDomainID(ctx interface{}, userID interface{}, domainID interface{}, preloadRelations interface{}) *Repository_FindByUserIDAndDomainID_Call {
	return &Repository_FindByUserIDAndDomainID_Call{Call: _e.mock.On("FindByUserIDAndDomainID", ctx, userID, domainID, preloadRelations)}
}

func (_c *Repository_FindByUserIDAndDomainID_Call) Run(run func(ctx context.Context, userID uint64, domainID uint64, preloadRelations bool)) *Repository_FindByUserIDAndDomainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64), args[3].(bool))
	})
	return _c
}

func (_c *Repository_FindByUserIDAndDomainID_Call) Return(_a0 []entity.UserRole, _a1 error) *Repository_FindByUserIDAndDomainID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByUserIDAndDomainID_Call) RunAndReturn(run func(context.Context, uint64, uint64, bool) ([]entity.UserRole, error)) *Repository_FindByUserIDAndDomainID_Call {
	_c.Call.Return(run)
	return _c
}

// HasRole provides a mock function with given fields: ctx, userID, domainID, roleID
func (_m *Repository) HasRole(ctx context.Context, userID uint64, domainID uint64, roleID uint64) (bool, error) {
	ret := _m.Called(ctx, userID, domainID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for HasRole")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, uint64) (bool, error)); ok {
		return rf(ctx, userID, domainID, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, uint64) bool); ok {
		r0 = rf(ctx, userID, domainID, roleID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64, uint64) error); ok {
		r1 = rf(ctx, userID, domainID, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_HasRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRole'
type Repository_HasRole_Call struct {
	*mock.Call
}

// HasRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - domainID uint64
//   - roleID uint64
func (_e *Repository_Expecter) HasRole(ctx interface{}, userID interface{}, domainID interface{}, roleID interface{}) *Repository_HasRole_Call {
	return &Repository_HasRole_Call{Call: _e.mock.On("HasRole", ctx, userID, domainID, roleID)}
}

func (_c *Repository_HasRole_Call) Run(run func(ctx context.Context, userID uint64, domainID uint64, roleID uint64)) *Repository_HasRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64), args[3].(uint64))
	})
	return _c
}

func (_c *Repository_HasRole_Call) Return(_a0 bool, _a1 error) *Repository_HasRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_HasRole_Call) RunAndReturn(run func(context.Context, uint64, uint64, uint64) (bool, error)) *Repository_HasRole_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRole provides a mock function with given fields: ctx, userID, domainID, roleID, tx
func (_m *Repository) RemoveRole(ctx context.Context, userID uint64, domainID uint64, roleID uint64, tx *gorm.DB) error {
	ret := _m.Called(ctx, userID, domainID, roleID, tx)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, uint64, *gorm.DB) error); ok {
		r0 = rf(ctx, userID, domainID, roleID, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_RemoveRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRole'
type Repository_RemoveRole_Call struct {
	*mock.Call
}

// RemoveRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - domainID uint64
//   - roleID uint64
//   - tx *gorm.DB
func (_e *Repository_Expecter) RemoveRole(ctx interface{}, userID interface{}, domainID interface{}, roleID interface{}, tx interface{}) *Repository_RemoveRole_Call {
	return &Repository_RemoveRole_Call{Call: _e.mock.On("RemoveRole", ctx, userID, domainID, roleID, tx)}
}

func (_c *Repository_RemoveRole_Call) Run(run func(ctx context.Context, userID uint64, domainID uint64, roleID uint64, tx *gorm.DB)) *Repository_RemoveRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64), args[3].(uint64), args[4].(*gorm.DB))
	})
	return _c
}

func (_c *Repository_RemoveRole_Call) Return(_a0 error) *Repository_RemoveRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_RemoveRole_Call) RunAndReturn(run func(context.Context, uint64, uint64, uint64, *gorm.DB) error) *Repository_RemoveRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
