// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	transaction_manager "github.com/PhantomX7/dhamma/libs/transaction_manager"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// ExecuteInTransaction provides a mock function with given fields: fn
func (_m *Client) ExecuteInTransaction(fn transaction_manager.TransactionFunc) error {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteInTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(transaction_manager.TransactionFunc) error); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_ExecuteInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteInTransaction'
type Client_ExecuteInTransaction_Call struct {
	*mock.Call
}

// ExecuteInTransaction is a helper method to define mock.On call
//   - fn transaction_manager.TransactionFunc
func (_e *Client_Expecter) ExecuteInTransaction(fn interface{}) *Client_ExecuteInTransaction_Call {
	return &Client_ExecuteInTransaction_Call{Call: _e.mock.On("ExecuteInTransaction", fn)}
}

func (_c *Client_ExecuteInTransaction_Call) Run(run func(fn transaction_manager.TransactionFunc)) *Client_ExecuteInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(transaction_manager.TransactionFunc))
	})
	return _c
}

func (_c *Client_ExecuteInTransaction_Call) Return(_a0 error) *Client_ExecuteInTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_ExecuteInTransaction_Call) RunAndReturn(run func(transaction_manager.TransactionFunc) error) *Client_ExecuteInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransaction provides a mock function with no fields
func (_m *Client) NewTransaction() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewTransaction")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Client_NewTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTransaction'
type Client_NewTransaction_Call struct {
	*mock.Call
}

// NewTransaction is a helper method to define mock.On call
func (_e *Client_Expecter) NewTransaction() *Client_NewTransaction_Call {
	return &Client_NewTransaction_Call{Call: _e.mock.On("NewTransaction")}
}

func (_c *Client_NewTransaction_Call) Run(run func()) *Client_NewTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_NewTransaction_Call) Return(_a0 *gorm.DB) *Client_NewTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_NewTransaction_Call) RunAndReturn(run func() *gorm.DB) *Client_NewTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
