// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// ClearRefreshToken provides a mock function with no fields
func (_m *Service) ClearRefreshToken() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClearRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_ClearRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearRefreshToken'
type Service_ClearRefreshToken_Call struct {
	*mock.Call
}

// ClearRefreshToken is a helper method to define mock.On call
func (_e *Service_Expecter) ClearRefreshToken() *Service_ClearRefreshToken_Call {
	return &Service_ClearRefreshToken_Call{Call: _e.mock.On("ClearRefreshToken")}
}

func (_c *Service_ClearRefreshToken_Call) Run(run func()) *Service_ClearRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_ClearRefreshToken_Call) Return(_a0 error) *Service_ClearRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_ClearRefreshToken_Call) RunAndReturn(run func() error) *Service_ClearRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
